# Utiliza una imagen base de Apache
FROM httpd:2.4

# Copia tu código web al directorio de documentos de Apache
COPY ./tu_codigo_web/ /usr/local/apache2/htdocs/

# Copia los certificados SSL/TLS al contenedor
COPY /etc/ssl/server.crt /etc/ssl/certs/
COPY /etc/ssl/server.key  /etc/ssl/private/

# Configura Apache para usar los certificados SSL/TLS
RUN sed -i 's/Listen 80/Listen 80\nListen 443/g' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's/#LoadModule ssl_module modules\/mod_ssl.so/LoadModule ssl_module modules\/mod_ssl.so/g' /usr/local/apache2/conf/httpd.conf
RUN echo 'Include conf/extra/httpd-ssl.conf' >> /usr/local/apache2/conf/httpd.conf

# Exponer los puertos 80 (HTTP) y 443 (HTTPS)
EXPOSE 80
EXPOSE 443
