version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - db
    networks:
      - mynet

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - ENV_BOT_EMAIL=adri_mrtnz@hotmail.com
      - ENV_BOT_PASSWD=BotSpaceApps2023
      - ENV_BOT_COOKIES=/app/cookies
    volumes:
      - ./purpleCode/cookies:/api/cookies 
      - ./purpleCode/spacebot:/api/spacebot 
    networks:
      - mynet

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: passpass
      MYSQL_DATABASE: bookspace
      MYSQL_USER: user123
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" 
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  db-data:
