FROM python:3.11
WORKDIR /api/
COPY ./purpleCode/* /api/

ENV ENV_BOT_EMAIL "adri_mrtnz@hotmail.com"
ENV ENV_BOT_PASSWD "BotSpaceApps2023"
ENV ENV_BOT_COOKIES "/api/cookies"

RUN pip install -r requirements.txt
CMD uvicorn api:app --host 0.0.0.0 --port 8082