FROM python:3.10
WORKDIR /api/
COPY cookies/* /api/cookies/
COPY spacebot/* /api/spacebot/
COPY api.py /api/
COPY requirements.txt /api/

ENV ENV_BOT_EMAIL "adri_mrtnz@hotmail.com"
ENV ENV_BOT_PASSWD "BotSpaceApps2023"
ENV ENV_BOT_COOKIES "/app/cookies"

RUN pip install -r requirements.txt
CMD uvicorn api:app --host 0.0.0.0 --port 8082