# Utiliza una imagen base de Apache
FROM ubuntu/apache2

# Copia tu código web al directorio de documentos de Apache
COPY ./bookspace/ /var/www/html

# Copia los certificados SSL/TLS al contenedor
COPY ./certs/server.crt /etc/ssl/certs/
COPY ./certs/server.key  /etc/ssl/private/

# Exponer los puertos 80 (HTTP) y 443 (HTTPS)
EXPOSE 80
EXPOSE 443
